### PR TITLE
general: Add ESLint, Flow, editorconfig, prettier, Jest, storybook

### PR DESCRIPTION
**Pull request by oreqizer**
Note - storybook doesn't work yet.

### CODE REVIEW

**Comment by alexedev** [comment]
I would prefer not to have .js instead of .jsx

**Comment by oreqizer** [comment]
Done

**Comment by alexedev** [comment]
@oreqizer I fixed the storybook in the new commit, according to https://github.com/storybooks/storybook/issues/3624

**Comment by alexedev** [comment]
@oreqizer I would remove those relay related rules and then it can be merged

**Comment by alexedev** [comment]
@oreqizer any changes?

**Pull request merged**
